# Generated by Django 5.0 on 2023-12-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_function', models.CharField(max_length=200)),
            ],
        ),
    ]
